### ISSUE TITLE
Give this repo a license

### ISSUE THREAD

**Issue by ghost** [svmiller/steve-ngvb-jekyll-template#4]
Since I'm using this template, I want to know the license. Unless I'm mistaken, this repo does not have a license specified. I believe that this repo might inherit the MIT license due to it being a derivative of jglovier's repo ( see https://github.com/jglovier/jglovier.github.io#joelgloviercom-  for license mention)

@svmiller , what do you think?

**Comment by svmiller** [comment]
I think so too though the thought never occurred to check. I added one now.
